[esp32-mqtt-publish]
mqtt_user = "esp32c3_rust_board_publisher"
broker_url = "mqtt://broker.hivemq.com:1883"
wifi_ssid = "Is_it_JoJo_reference?"
wifi_pass = "WRYYYYYY"
topic_name = "default_topic_name" 

